[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "db34bc4f6c68db812ff6cb67dbcf21e0038a9f43"
os = "macos"

    [[FLINT.download]]
    sha256 = "f1f45c1cc02e6f5718d81ad1a4b5e0005781f7f965a63f859d41ef5f67e84924"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.aarch64-apple-darwin.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "6dcf50ad4bafa8d94951327690861bf363e5d1b3"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "ef91fa2453d1bc8d55558b28b21d439578d64856a6981df76ae0ea4a1eb846a7"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "4791bf1ba9c5c62fea857a4186ec3d1733f5bc59"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "b1318b0740c0f9a83529b6f924b288f1b3dcff9cd45fc216b0f603ae94deb2fd"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e4d0206ee78141e09c72405f2279b1279ac250e2"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "4a87266bce3dfe1d257381ab92da085aa6e196cf914303161825c76c4e4d86f8"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.armv6l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "56b85e357fc3070976221384143848fc137572f4"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "4ca1e1f37a485174b6905b99464c2b5d80afcd1f5645ceb79297852635f697b9"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.armv6l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "80cc5fc4cb398a0d95aff8dfc4693016442e0158"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "d482ae20b4db2b7e07c5aaa6475010ffde051d074f0a4eb954fa6872ee4e03ab"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f96ea378e6f2f927900cbd15eadc360a66f6177c"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "54b33aaf57deccb0a21f3d41238351ef70fd6667f9cf35925794960878d9beec"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "bebe48b943dee97d7b5bd07b1464fa49f3ee2b62"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "5e62bf06ed8a2a2755e33518b115a26f6fb5ba24edd327ccb3815e67e0744a14"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "9e3cc355e9367ced2a86276c3bf1cf33778a9754"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "6dfc2fa208627112ee05f294ab22eb0ba706605df0047ec5df7703313d6df511"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "2620da13cd3a1a5291065f53dce9daeabc491562"
os = "windows"

    [[FLINT.download]]
    sha256 = "dc36b54a22b718dcf84989e15bbe64df1046bcfebb315d08e1c6320301038cfb"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "acfc46ea2ba0715d9c56d705c4e56c71b6875a0a"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "62a3fe54ebf85ec05260ca1920f017247c3920a7089a811499ec2fb167b7259f"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "88587517a5f140159b82eb4565d4eed7cdce9c33"
os = "macos"

    [[FLINT.download]]
    sha256 = "f87039931c6986175b1b75d6480aa2eb88c656a6f4ce6cd9212e53d6102688ae"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.x86_64-apple-darwin.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "1ba00c60c88d0e597b30673d0921d15ada9cf9c5"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "363a5dac3eee2173d1b7e494099bf248385219d20dc31e6fe438640f6de9be24"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "aad16fc2ee67d06625e21f40acb891a9d26a09c5"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "688dc0a41a87ff4f9910ac24f7f132cb3f0776edd71c6814b7f30cc8ae3f237d"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "3f7b0f9a50be5e64668c2f6031db6b68f08e9812"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "882ea53719fa27a900f8366d054297461dc5aad4fadb2241a0f5945524ad6099"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.x86_64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "9f95d5e6302aa7959f7b9992b03aa270e2e44aba"
os = "windows"

    [[FLINT.download]]
    sha256 = "f068c17abfc99ab7449c7e90de2c9a78038eaf4ac7b65ac94c10d9a4f800614c"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.6+0/FLINT.v200.900.6.x86_64-w64-mingw32.tar.gz"
