[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "e187dc9916d666a540b42fe8e1dae7e5f083c4fc"
os = "macos"

    [[FLINT.download]]
    sha256 = "8655a275a67bd3d7970b69e2ba390bf8cfb7b887793c27632b5f7afbfd8f5c3d"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.aarch64-apple-darwin.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "20522c8125203f04a697997d366a202006d587c5"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "35fcd56f41873359af5c502568e619847cc79ce7fa0a9a4bd9e2b30b49d5f8fe"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "1165c3bf5bf0d185a4f7315dfe6b4eb52c1fcd35"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "e230470444f77a2ce49b2858407c55b4fad0b3285c1459699a2bd4b5ea53d25c"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b050e0d6d2873a8b9139d3513a1e5dc90b0fcbd2"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "69190d8bdafd9867796ffbfbbc37beb8234ef621490f569e6a01dc70ad3da0c9"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.armv6l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9690d43366dfa2101926a0dda5ed77fc9669aa9b"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "df2e84385521393c5c55a829beefb171d4e4554787311698c90252e1639a4718"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.armv6l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cd7f57348f5b3f3171ad58c4fadf0cba5e52e20e"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "ba6397fec29f1ae71a061ee0e2761bae0f2a18c3508c1874bd68a9d2611cc01e"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "87a63ab5c2ec059c1b8c4104defc082427059dc1"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "a76567026dd66e3abbacf196e3383645fded2cd0fa63d28f5058bd73084e084c"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "06d9b599f4d4433b5ca491b2310ee6e1a66a8018"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "b12e8196d6391aa9f2467e58089fb490a448f21ede1e92857c6d5cf91e1ca6f6"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "e48ca042eb7626364205412a28d3dfdf43f9653f"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "f16d2528f44246a0ad023d5eef13648f88fb45f70c8da91ad89decca69ae9f87"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "b791ce83675aa73873ec3cdc05fe533fd9b7f12f"
os = "windows"

    [[FLINT.download]]
    sha256 = "86cae8ed12744ac0dd7b351ab8fc8f69c27619ce78ce47467bd229a739202bd5"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "97db491aeeb56453ccf93b56de03a8c69f2e854e"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "94b23db62fe0a0cffd39cdd3fe564d9b27770e3f59bcb8a3bb3a531018fc2fdb"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "edf79bc925fa465cc487e6414432e55f19e5a534"
os = "macos"

    [[FLINT.download]]
    sha256 = "03719ba98e5c7e82b91b7614665b522b5a35c60e8276d520576433d87a24aced"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.x86_64-apple-darwin.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "9636cc29942bc35dc012750182a847de9772e381"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "33a6948835aadb702dfd54fcf577c1418cf94a579bae1b1d3a35042539691360"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "64c335e73420db4ffafca45f9a5617a9ee5df795"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "4795d9975aae7349075e07a55753a6f3be99ddbdf00c63b22a701355ba543b5f"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "921681f7b87ea9b7ab21b29bf83dd762b83e7f1e"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "5af46dae8aa80a0a599511e8f1ee6841c45d7adb88c6617865c237f0b93df676"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.x86_64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "5d0fadcbed80196cd744bafbe4164b5741e9486e"
os = "windows"

    [[FLINT.download]]
    sha256 = "548d49cc59838b98bf079c99b5b3368ffef53eaf2856d904decdd1f4a483e537"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.2+0/FLINT.v200.900.2.x86_64-w64-mingw32.tar.gz"
