[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "4d36ad8fe33e38e0d72c0fd3c975d3f44a3b1698"
os = "macos"

    [[FLINT.download]]
    sha256 = "2c79cdbbb560576c9c3da9664b60088a4ee45fcb16ffa80cd457107651d85450"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.aarch64-apple-darwin.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "e8a94805b1beee77e9f1fc83c6f068281f27b0a1"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "69cdc31a67b8181a577a74ed9957086002c1dfec10c8cadcf16599db3f4206a5"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "aed544ab25c674e97c6e7c533160356ff1ec200b"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "e0ff356313cc8add17d24d392bf591bd11f087c0423ff79177f619f3d80ceea8"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "04deaadb4e9927c7f5e4b60a6aec391f756e3cc6"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "7921a5b11949c0ded2d361d3e2e8cdaca15bf89c9a69b27d05103f6152820c9d"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.aarch64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9bc7193432a987056ecebe1db7123aedb2119088"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "0725205eed0a5512bc74f22bfda099a3085c224c5f04db07c5c1c56152681446"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.armv6l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6cefe112327474e079305a5417fde748f9133b7f"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "6ac8ad372cc3ae9417268bd5e44541b5772dcaa6c5220ef7eaef1c4bbdafe26c"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.armv6l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0e90cac8fdc477b4c0000dbfa7143a3822d6e9ad"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "e20f842357df0726fe39f53e15e313caac89c84df619e370aa8e6daf984b65ea"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a52f48971130235cef170b878de981f748a26b37"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "520ac4f8a9deefd504c9deb3543ac4045c414a5d3f5a49287e7e6d88de3f48ba"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "a4ed8f6fafed151086ea917727219ee496868dc2"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "6ee169deb961f7737ef2e042869b63a38be86e14e88eca7fe03adfcdcd157090"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "e9044327d1d0aabdbf53845e3118ad2b1ffa2d41"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "0f91efa6241bdd57ef11eca0bb09637886a95b2cea0b1d9f733d6aeeb097c58f"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "28bdbd77486f24e91afd59b73180aab5c14bb1f5"
os = "windows"

    [[FLINT.download]]
    sha256 = "53f3d605fd4be92a89dcac2fb0437c7445f3f22392bdb0b8e66a8ecc859b4812"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "3dd693e5dbbc32eba1ac958428fb4662e3afc427"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "a03a7d343bd17dba38b956e2d4ddbdb1f4796e5a58a49eaf84b8ffe874975ae0"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "riscv64"
git-tree-sha1 = "3d7c04fcbf22fc47d72bc792d96af7b097500873"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "3a22bc4d91d9e82fcc1cfae7e55172aa96858b5d8f70483c9a9b31bb3a7d85e2"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.riscv64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "20b98e0684639994706e1408f74b6b291d7f0094"
os = "macos"

    [[FLINT.download]]
    sha256 = "1d7d662701174b95817b7f6b30e56a137734069122ab0aab2243306fb0b6ca64"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.x86_64-apple-darwin.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "f1fbaa2f3bc028c94a47175c5481b8e241352d3c"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "1eb6d1452fa7702ab41a5c62ca86ce0f8adcda682197e500ab8745d4fc45d133"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "3f408ad76d85587f82ce32e08ce88d23123c6bac"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "b0efd36f3e02a0639659400e4e8a44c4472ee90e5ecc50f36fc56f2177809652"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "b436b2b8aa948b4554708a3828e8450d51e2ddb2"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "c29620456aefaaca43ff2dd9d279d2bc04ce45051505659129b555629c8bb7a3"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.x86_64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "5d15d70116bb811469279722ff0d624badf351b8"
os = "windows"

    [[FLINT.download]]
    sha256 = "6f5deffdad56c39a349540842eedc398a529944b4db1ce338031cf02e9bd586d"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.1+0/FLINT.v301.400.1.x86_64-w64-mingw32.tar.gz"
