[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "05cb43a806e868c08ecc69690cb6a28b76415b7f"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "5b14f4c383488c116c2a1755d90bba2c8d73b40efc51e0f0594e5e28dad6a0ee"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.0+0/FLINT.v2.6.0.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "bd19fbf36d0bd4575445687280b5ad344418462c"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "ebeba3bf7a9e6007cdb2cc0d5f8f43e5dbd0ba51e0a5b8ae550e1c7364a280c8"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.0+0/FLINT.v2.6.0.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "armv7l"
git-tree-sha1 = "37df501b326c587cfef0fa7682f4210a8491f6e0"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "d506142b9a4744e6e8ea8279c6097d7d8ccceb99a830d82d84f140d7fe4dc574"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.0+0/FLINT.v2.6.0.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
git-tree-sha1 = "54b28b8efe863223529b9a34d8ab8ab673495f6e"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "07308f6bf6db8d3c7e7be043217985e751441df57baf14702ae00ab074499fc0"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.0+0/FLINT.v2.6.0.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "d4171e11ee5bbc6a5f002ca220e74f8f0eb4dfda"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "d92b523d17e68890f512f90709918dec6a42ff048f511eefefd726283156b8b9"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.0+0/FLINT.v2.6.0.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "1cfe3037545c34bb6f8639c62fcf065125a3f909"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "024ed3f104a92b34629f36d9bb9ca10c8e75e2a129df3974ea6ef14c94b3c438"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.0+0/FLINT.v2.6.0.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "bc59ce12b0ee7e0bf6e8e19d6bcfde59ec6f8b44"
os = "windows"

    [[FLINT.download]]
    sha256 = "21b57a6458e3398cb132d1989819387132553235d95567942eda95a395a85c6a"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.0+0/FLINT.v2.6.0.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "b2a30eaffd24fb644590d0959276726ddf2ac48a"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "b6d37bc7ba18a171f7b56a8c5c2eb857c32cf76827cf540446e8f086ec9392cb"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.0+0/FLINT.v2.6.0.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "d00fb6545de3282b9c62dee60c1ccfa160912432"
os = "macos"

    [[FLINT.download]]
    sha256 = "0e39a384e45f82bed87f3b472e768a17ade4a5773770c3359b38854e974542d6"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.0+0/FLINT.v2.6.0.x86_64-apple-darwin14.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "f8ab6efa2a747a5e74034fae3d543b6e2948b527"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "8137bd0cf4b0fd3808b2d4bc574c005a40275a272ce4e64fc5ee1a1855ae2fae"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.0+0/FLINT.v2.6.0.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "667ed4fae687c317b10248b9379b94457e4acedc"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "dd63d941088ef5232207f6cfd2cf02f1003b969ec78c5b4e85ee32578087d273"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.0+0/FLINT.v2.6.0.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "a0c3fb63a61114bf1c61dff42f0a1a4a0d8a1b3a"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "19820b1fed197923d9d152df213fc76cca8b38f73a999391653c97d8d4327ea1"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.0+0/FLINT.v2.6.0.x86_64-unknown-freebsd11.1.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "be49eaf3a4a429039639e84554e700ca8c497077"
os = "windows"

    [[FLINT.download]]
    sha256 = "9ccf3eb9b8ee8d2cfcd501e9e44273ee25a6cd0e903daf3fc2861eb9ab831a12"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.0+0/FLINT.v2.6.0.x86_64-w64-mingw32.tar.gz"
