[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "22bfb1b45d0e5594b262901b35eb9c634a64ee08"
os = "macos"

    [[FLINT.download]]
    sha256 = "b51408fad21dac872f6533d55d88746ae6a0a83926d0782500823378c7f9d583"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.aarch64-apple-darwin.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "f0a905b9d81bda67260dde2234536c0712d9dffc"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "a2f542960777bb22fcc902100d9f02f9ceef45034ce996373f29eef36a237448"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "4d62f7569cd74dc9735bcc20f337ec855b657ffc"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "15b7d5ca72df6aa3f3d3aa1790bb6af5119d420d6f79d8d849232b870593ebe1"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "75f0b0b3203d5409d2da93d1b2121b6a2c0e3747"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "566aa3261bc32e38bb3f9d6cadb2aff04a42ccdf34119f1a18822a82e3ea750d"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.armv6l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7dcb8c6f30a21ac5b32ed0de683387f26168c2d8"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "2e807bd80d1df315bbe020ffcc4807cbff279d1b071fa172ea64a14765e34dc5"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.armv6l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "905a13d61cb60e84178d4393ead57e2956a6eddb"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "005b412d55c27dbf1a07cabbeb451ea5a23efe7cca9f0c969e3d840b7e924876"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f291a420c08144c0311933f2fa2b44b15ff7f346"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "483121042c3ab547921fadd98f78f4e7e493a1d70d30f219e45edf0517a8ad36"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "04ebf0b535f853336102e8b7091cf34fa9746475"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "aa3078232ee3ed6e9a298cd47360d340679148d71d1afb21fb5b709e132cc8b8"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "fd91b0f3192cdc83db2db914b1e981ebb7e37e8c"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "45b86d29344d0627e9711fc4b0fab7e43f92fcd42e6349e3e211df8a63cd2af5"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "47f89df29a0c798224a6d45ecf81bdea89661e10"
os = "windows"

    [[FLINT.download]]
    sha256 = "2d313fa9098870634a7868be5ee8f00a514b9182f5cbdbe76315ab547ff78b81"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "2ffb74ed052902bd45c98336e8580fdec2268fb6"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "6c65e12569b0b5b3c2d157219ba6dbbdbdbfbd7ab4c48967cb000800d9d69913"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "3c63914d5577dfe2cf06ffe0984808929cf40ea6"
os = "macos"

    [[FLINT.download]]
    sha256 = "f97a6ed9e360159cd37bea984fefb557efa539ab4025f99042f9fcb651159e1d"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.x86_64-apple-darwin.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "d17a380c40e78a5a5eda48c0341fe190148ccbd5"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "a4e40d2eaa2626134425e646a4ed964b2bc643785905f4c8e19faa6f4edf3295"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "0da0e55c2cfad682eb6ee2083d9e4b3c31322172"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "b732086f854bd99ff196e2cc3a4c1e7ce8382bc0b8f152f1863ff60be57693d1"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "6626ce1278bad3d6021a02cf80eb8b5e23981b53"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "3a6133b4da4f97f5a2e8c075ca96022032d379687de2929e73857cd5dc7ac4bb"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.x86_64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "2c6d1e6b6213ee8c2d04e172f768efd88503807b"
os = "windows"

    [[FLINT.download]]
    sha256 = "c885d39fe89ac7617836d4264fc5a1d8e6ae722db30ea348e1e9aa0052bebb81"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.5+0/FLINT.v200.900.5.x86_64-w64-mingw32.tar.gz"
