[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "844cd2dc9048e099d7f37f6dd002eb89d2e4ed82"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "44e901e79f2cb553c9aaef8e4c9a7f7cc038e22b8d11b9dd0c133043d364e018"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.800.0+1/FLINT.v200.800.0.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "0e9dc9008ebd351110e8c10e59541931ffc95ba3"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "38bc8d8d9e50c221e70cefaf423c5859199739c479b4bd444434caa790c0d747"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.800.0+1/FLINT.v200.800.0.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6de2af81211cbebe2869c3f61e265b100e663760"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "e104acf4a8ad41dabf684e26f2b5f41ff0d66b0e93cb679d45bab2a70d721366"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.800.0+1/FLINT.v200.800.0.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "88c9eacceaf7aac2908aa954799c9c0976fec222"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "58e6b18478e03c42480cbbb2bf3a8ea8dc85da8dc935b95ce95b814ac81e43e9"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.800.0+1/FLINT.v200.800.0.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "9c8d9cd25ad3157bf17d248af9a399efeb771265"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "8230947cd6263d392cc85210431b6bb09460195897e7b857cacc6bf168e9befb"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.800.0+1/FLINT.v200.800.0.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "f92db7dadcd6e7b630653688455586ce2a7827b4"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "8d1b8a6afdee954296773743f3395711489c825ae7210303b7c1746f3c0c66cb"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.800.0+1/FLINT.v200.800.0.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "97a96e73a9ff93f0f21fdd6f350106fdddd5086e"
os = "windows"

    [[FLINT.download]]
    sha256 = "f63ad8e6c0dfd2735898bd37adafba2b596e8e5afdac66d7154e669a1672012e"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.800.0+1/FLINT.v200.800.0.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "6ca6f3a9ab8fe75359052273e0ef12b16988c5e5"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "7d78618bcd315df782395b52697dbdedacb98896383cd542f4bb376a32036ae6"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.800.0+1/FLINT.v200.800.0.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "9f9bbec0ef0f6c23feda30aa8e7e45dbf07a68dc"
os = "macos"

    [[FLINT.download]]
    sha256 = "1a5f2d12bde03e5049053df3cf8d94a6007afedd68a9470f24b0ab3c1df49366"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.800.0+1/FLINT.v200.800.0.x86_64-apple-darwin.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "b05c1d995bbe9c123f9150b369e508bbdc16d6ed"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "c2a2339d2981ec8b3f7530ccbed4853233fe1e79fa7217f65823c64d8765b50e"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.800.0+1/FLINT.v200.800.0.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "be63f4f76e51df33507a3dc58f193f431d7299c0"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "a172acddd32cfa29e88c6cc03f721ce6d0ed8d3832176cd281683ce9233e92d2"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.800.0+1/FLINT.v200.800.0.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "4ac3b40767d1e896076ebd5b34cb54244630e5fa"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "c2e0f58fb544beb0f83b57787b89057bf9e8949da76062e901a8ccb1fa734507"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.800.0+1/FLINT.v200.800.0.x86_64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "3bebafb32e46235f7853f48535826917276ab883"
os = "windows"

    [[FLINT.download]]
    sha256 = "6353f794f418ae9f8f588748e74f6a42b7af6d18ba73ad2bbba68be623461c93"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.800.0+1/FLINT.v200.800.0.x86_64-w64-mingw32.tar.gz"
