[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "becf53c2ccb9145c589aafadac67ed0e89718d66"
os = "macos"

    [[FLINT.download]]
    sha256 = "2546e95ccb82e40b14b2b96717d03f5074ff206ba77503f3958f614a95c6b834"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.aarch64-apple-darwin.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "c37e75ccba105ac26a5cb90897da169fe77b15c3"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "a808d314c3d1b994f0f52260c1b36405e97a14013d39a2294f2a404a0a54d4c3"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "2caa91805c09a2069965f8f20a5f3ae6b2aa265a"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "355205eba49868a5092443ef281fe19f3c8d4c14325622beda7ef587368f9e64"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "57a0747524f7f193d124b7975f763577140eab2b"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "3ec4356f30e08f3c00512eed70491e69e38146c4acfb260f7a72fc9d04df207c"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.aarch64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0628b15cb65b20daa691b79a9f0d2b34c37bc4c6"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "b17125fdf4559cd8f2c79dd2c4237801049e78b6c6040b33b682fafca2afd25a"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.armv6l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f7fb37c8c5169ceb6abf6ce611b5764241f69cdf"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "66a78f833b242522e26e4fe4a88b226c0a86da67536cc02df636af6b543cd099"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.armv6l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31714dc637ee52f5f6197fa82f1c4a7386fe19a6"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "b87fd95f43d7e435a4d65f07e57f7cae6ac13270bdb7460a62390bb33a0ad7b1"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f274bb731094929f69b93fdc3ff913b0211f9695"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "2889f77493c79e4209f606ea3ce4df6d8d6d3a362c10cc4973936f2bd41fa7ff"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "38f0091674fa43c2eb296f505b1d12fe90eac00a"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "0cea48654af05b39f1300a057bf6d0c7eb1d0bab7bd8d5ce57b49f29066a169f"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "e646e0e30a03b248ed99b9dfdfb9c08a1ceccbbc"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "2fb09eb5da21bc2b3fe29b3395d9ac7ebc1f8a1574790346f1b4532b58244fe4"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "14d505ff5f70f95045324d10935e3f93ae2926c0"
os = "windows"

    [[FLINT.download]]
    sha256 = "9b88d801ffbce5c06a800a868c815a4bbe0ac251156371e3a55f2360f50b3192"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "8563c4f22d0d860532fcd88e18e869c00ac84e18"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "c0576ec321bc5e43737092e502b67ab85207fa5b2d147c4bdf158d3693930609"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "riscv64"
git-tree-sha1 = "96a2f3e9399fe56eda3443a0711b12da90e554e3"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "869a44a71f8aa541c8978d4995699f1fafa3b19ee0887e18c85e5b60ffde8384"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.riscv64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "46c510135b41c7c7ee983126ac24a697ab095be9"
os = "macos"

    [[FLINT.download]]
    sha256 = "6b2a19fb2d7b74c0c22e799dad2c9a9c9a4de5aed704eabceb4d249e6891c4dd"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.x86_64-apple-darwin.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "dfd4b78d70616c6fc8d0a40dd7a37c68cddc7b2c"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "6a2052a211f5b0d2ec7fc12a6b48e7ddc6fa27202a5a9cdd4f2745f89af9e1ef"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "aae359f2b336df0c86b4fcce96f681d4f9fc2416"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "8ff2a0970e7929a68186dda9bfa9aed8df39cc131e1dc1d3595573c0d9e14175"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "6b1954bf0399215939b2509aaa7fb819a9a35ec3"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "ffc85bcb978b0d20372d7ffc8008ac35ecf05b63bd68c788484fbb759b56eaec"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.x86_64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "dd9f2e9c53119244253b47eb32682ab3c3aa44a0"
os = "windows"

    [[FLINT.download]]
    sha256 = "f925ad2a9804118c845d49928a2cc4cc069ced1bb72d80d7e77612dfbbd0d7fe"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.400.0+0/FLINT.v301.400.0.x86_64-w64-mingw32.tar.gz"
