[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "9552131726f3d19dc3867b9785e598da5548e77e"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "f53daaf03c28a86d070077f2d247aad0f11dca727549f1a76eedcf73c6377eb5"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.999+0/FLINT.v2.6.999.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "6faa738b3816d280110e99844b0233487a2b41f6"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "8ecf3bbd5414a9ef5efcd8243e4f4ea8120c084edc7b14b496a6f6ecf0759949"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.999+0/FLINT.v2.6.999.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7f07f44160c319e503a874a55e1daa504e66e260"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "477e809d1c91f7cd04a777d2344059f537170ca625465d70a220564c14371d11"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.999+0/FLINT.v2.6.999.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8d73e812df602515a11a3a2113e300861c3507d0"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "d457eac7e033dbc8f5d78fa59537f7b5085c4c91ea2c64637d4bbc30302169ae"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.999+0/FLINT.v2.6.999.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "1264ee3bc14d9da1edc0a15bff9405ee53a31c2d"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "dd91e9962c981b321589077b6133e59dac7c0a5c38e7edc3fdefdca51a2945fb"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.999+0/FLINT.v2.6.999.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "2b7f81ffcf2359ecc0f84379a384a55e22cc534f"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "37c5c32bb92cc5b413f32da007ec78f7f0c449aa733ced9d8b015381c01fe63e"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.999+0/FLINT.v2.6.999.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "d1e29daa7d52467ace743ac54696ec25be60c602"
os = "windows"

    [[FLINT.download]]
    sha256 = "aa31235f25832d72473addf9a9144c3d4c26a3957f7a33c19939b0ff5f9a5c4b"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.999+0/FLINT.v2.6.999.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "b0a6bb783284069ab12c1eb0063fdf337f67247f"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "6a46cbc9d3dabf6566bbeeedace87453a8fd4a165c24e602afe7e9186826bd07"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.999+0/FLINT.v2.6.999.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "598817fdfdb15bdd656b2d99e3832249c11bf28d"
os = "macos"

    [[FLINT.download]]
    sha256 = "f713542986ad1c64b10af1987702168b791ccd4aaf35164928e36ad8d9c04522"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.999+0/FLINT.v2.6.999.x86_64-apple-darwin.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "1044d53df5c9b92ac8102ec7ca6cde89cccfb848"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "9293c7a48696e50f29b43e19437275ea45fb2c94fac68005eb8037e115922606"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.999+0/FLINT.v2.6.999.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "27afe5a99059dc6480f8455ff6c43bfa84c769e2"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "ddfa739067fff4c39ec031d321f174a6854dc55ccf123368e416788ce005f154"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.999+0/FLINT.v2.6.999.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "d558a3633e63eb101481aa085c4489f60c8c50a4"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "5dc71c04184ec3e09e2c63bafe833a8d00faf457b4a0339390bbecb1383d19a0"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.999+0/FLINT.v2.6.999.x86_64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "a29ddee9e571a93371ebe8760a336695bb00d36e"
os = "windows"

    [[FLINT.download]]
    sha256 = "e92b95a7480a8b12f736b6f80cad72f3230e01a4b5ef053a21237cd2dadcec6d"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.999+0/FLINT.v2.6.999.x86_64-w64-mingw32.tar.gz"
