[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "578dcc48fde6c98d1fd61cbfa931dfa7f60f6af5"
os = "macos"

    [[FLINT.download]]
    sha256 = "68fe50eb7f117f004eada950d1f6a278a9ca0b2b4d411ef450f3931488873731"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.aarch64-apple-darwin.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "c230d66c4030eaf72aba0453ba75039f261087a9"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "a2fc497817f091a81355320d4fe2f98c925b1e5308db2b5b15a511a63df9f0ff"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "2d2e0a0c53cdcfb7fd6e7a14f1eca569ffa8bcd3"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "d5a1346e972124f5b769746ff5e148af95d70713aa4e5c89170556ea7cc54455"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "e0af647d0b3dbdf3439fc5a32d6d8d96326cb1ec"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "5564097b9ceb10b045e9d889900ab5c7f17ae3194c08969b1b70f799bccf4f02"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.aarch64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2b4c40d0ab5bdc4c4b41caba4b59697c6e1c9238"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "dcb76be2d0a205c7df30a9bad40b2bfae03fa413fa722b0fe028c627a7052c5a"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.armv6l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f58978050f7f6cf89e0f8e132d816dc9bf0ff04c"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "817105c458d98069f6cbebc2194b75e2e435a44d90c24a9b46fc870efdd0b752"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.armv6l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "50ce7f0e562f9211d6b75e47b449c22cfc053ba8"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "16dc2508bfb24aa1c31239ce6de3544f5d4653bfe54ddcbc0284ea5491d328d3"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cdb101f977d2da50c228f3805b328b19538e7b15"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "bf1d4193287dc845680b6201ea72176b86a311080b2713a2f8d8c4fa384aafb3"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "a47a618bec3099a611da4ba30d87ea2b9bc101c7"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "682386a678a8bb3c5bce031fa81807841dc167dbc239b35b7a0d233ef963faa5"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "bfb32307a59c3f0aa9e8bb3c0ac266f5d168539d"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "6a419b67428abd177e56ebb4aa6cba0391b537fe87a26d6cbea723bcf0ec7a5f"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "8ab3746fef7d96fe31f35b56095ded5345d343f9"
os = "windows"

    [[FLINT.download]]
    sha256 = "213a6f1965065dd1703f0c15c747507cff5cef0c8d2da441bdced9378c52b503"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "ac88c952530067d8546322a7799be8cb95ed5992"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "9be37ea5495170816280e89bae534ab561d81969eab890b246295f68654c73d9"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "riscv64"
git-tree-sha1 = "d779955a21652f76df6212610a2f91e4ea7711e5"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "ca2cf772cf01f6b5745e859eb16008d53cf2468ec76d106174732a556c3d7a6a"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.riscv64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "59b1a4942977441455fcf646b7315034d301665b"
os = "macos"

    [[FLINT.download]]
    sha256 = "5890834961eb59c2c32408a4763b50cf6ff08b6f67836996c34557a6bc84dce7"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.x86_64-apple-darwin.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "d4e1476875821d70a3aa98cf31710d83fc803a5c"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "9536446640396b2416602fe67c0415e53be57400f449cbb4f0f2c83a23ef7c16"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "0c7fe5fb77767bfca2f372f2e9b8bd5e3d1c6b99"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "ba545f46c81dad1cc4cfff7eee80e1d7a5db782aca98d557badda1fdd7d7065e"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "5cac4cc80d3d8bc04d324460da2797b40020e9d2"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "2718224d602ac8eff60c56429ee5beda73e1b40faf2d8dec757bdae63535c2f4"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.x86_64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "13b9da99f320778d96eca81b485c71ced962ddf5"
os = "windows"

    [[FLINT.download]]
    sha256 = "f73fbe29394537b9d3e7acd67b44943c917c9df7fb4795c1e40bd815a7d72c59"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v301.500.0+0/FLINT.v301.500.0.x86_64-w64-mingw32.tar.gz"
