[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "32252008cf233e9a004826d0fd2966dcdbb303af"
os = "macos"

    [[FLINT.download]]
    sha256 = "ffb64438d3594cfa8157e7a8d546d87ae6b0f739132371d2a23056264ef06012"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.aarch64-apple-darwin.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "491fc183c4c1348f90900b4bc76a075eaef392f2"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "c26f864bf0788dd2da745a4fe84d86b53825fd547064bd827a544590b8f91ddd"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "08f25af4e701fd43623174f93dbee0633b51b35f"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "717731dbece928fc910d968198aee407b0da21ade37886e8e0fed89b38ee3f8e"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "87db3766356592d7173c1e1afae6a16d82e78151"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "26b2b5be9134e6fa5e365068db091bbb0371de22f3a658f6af68d113bc9ca36f"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.aarch64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2bade83cf112c538289493899b52386ed7e052cc"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "849760d06500fc3d1eabcf97c1376de909c6dfcbfc765ee96bbf48416fa947f6"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.armv6l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "47c1fb3d9855506d0670b504ffb4a631c14e9628"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "46d5423f3d770055c03a06dcf45b97b6a599e5048437e301641bb7d511f3ace2"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.armv6l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a29800402ecc8ff9db1494c1a465a47cb4bae84f"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "8aaa13ded63c5238cc39f93641e2f4a6c0580d7f21f4d7a8fdfc9cfb8ecfc22d"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c57da3f4b0a71469fba6c4a3aadea00c9db29b8c"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "0fe34cb15a8b87cae87152d3f4fca0418e455057a9cc43df06029854e87c78a9"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "ca54223a21f4f18a860c209a7105a17b784197af"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "0dc608af15022efb6e73ff3a145b870be96b203fbd7a0e93e135e0446fa91b70"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "82ea6ee4d011f5214e05865fffe4182e60c3a199"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "812d23bfa3bfaec4ec9393faf579bb1b79ddf1ab0226f63d7cab9576f969b00a"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "ff0a45f58a73e10e39edc5cff726005507892c9c"
os = "windows"

    [[FLINT.download]]
    sha256 = "1c6bf292fbb88ecae02b052f02b35233cc14ba526dcea39f1ba97114cb935df0"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "13133ab2bd2c03095564b66e024346573d1497b0"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "ba039d8d7fbb24a203b7c3a1236fcaaa97464163f4dd8330948bf6445b3d974f"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "5ac5a9cc632c5f708b096a1aace6df866f2356ba"
os = "macos"

    [[FLINT.download]]
    sha256 = "3ee4f77e5b04714afb4759cb185afd70f29011e8833bcccb40b93f6c953cef6b"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.x86_64-apple-darwin.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "52069352b47eea1eed99c281508df43251c2d9b1"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "0b6bb1eebe73820f94ec12f0f2f01686af98cd4ddce54e7bd0cbdfc6e90274ad"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "d0d65c40c86ad12d013b19d221e55164aa90b8fc"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "2934ee90610df5fd618abcc59dd1f6b79fb93beb3ebc522b2a10c9129a576e07"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "b2fcafa9d4b69ad5817820497f8c4261542f5f29"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "d394ef212654655e9254fb3c9cfc0323ae9e6ec68d8863c3206115a734cbae3d"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.x86_64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "172a1b4a5b0ea9cc063ba5299fee4a21d66c4275"
os = "windows"

    [[FLINT.download]]
    sha256 = "5ee5fb552d63deb89aef489a393e3e45892fc3ec521afbd021fea773c6caeab6"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.200.0+0/FLINT.v300.200.0.x86_64-w64-mingw32.tar.gz"
