[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "e7bae9f75645357f5ccd8943f7f60603f111f741"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "4b18b7604e89cb590dad2bd799b8656ad01bd2243dba55f594e98ad53bbc41e9"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.3+0/FLINT.v2.6.3.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "82f11ad9715eec926306c88b776a880f7d36c2a5"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "9f9654432778026f7124fc0693effdb1543590670e8eda16b23609ca5f625990"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.3+0/FLINT.v2.6.3.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "armv7l"
git-tree-sha1 = "b818a4ddbcfd8ca3d7c24d940873453d58bc8530"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "a54d8b4b824a12a6b7740fc75e61bab51c3b000dcd11812c7ca6eb8c11b3dcb0"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.3+0/FLINT.v2.6.3.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
git-tree-sha1 = "c75677f505154a6dc0b4598b54c25a88fad44677"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "22afb927dc492cafad3734773bea0fe28609d5d64db23214c59fbdd53b5d3b9a"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.3+0/FLINT.v2.6.3.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "e068ac41b3a120f3722f36c50b5c47df53416f75"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "944c80b90c7dd074dfd215f89a83d294bdd8e2574dd4bd1caa5ddaf704dd1350"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.3+0/FLINT.v2.6.3.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "614442854ece8ca6612715e9cf31ece1c73999c8"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "928773f9e7ab730172f60e9d2829b924d7c0e389b30db0f48d363223ad6cc82a"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.3+0/FLINT.v2.6.3.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "57fd3bb2dd4dd435ed89cf9a268eff012c518776"
os = "windows"

    [[FLINT.download]]
    sha256 = "30f9602d766274e7e70c73a9c32bb13a1f38fdd0da37572e357b429f6ff14f1b"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.3+0/FLINT.v2.6.3.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "1ac1ca69e58a02eec4a4f8e858d843051fb74371"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "a54af32c5d037088edfee8b9e0216f29418cb6d2d56b10795e6f294c8d523c67"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.3+0/FLINT.v2.6.3.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "1bc1b4bb4fddc6f8a425f39d11a8dd77d16ff52e"
os = "macos"

    [[FLINT.download]]
    sha256 = "aa7be84ebc3c2fc47854916a77135297a0044dd5eb4bf735f89f746ef99adb9e"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.3+0/FLINT.v2.6.3.x86_64-apple-darwin14.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "2fa8ada57a2281a93080042ca38795366dd4cb59"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "e6dea82485f16668a3fa81e753f1354a4af9651db339adf64ea8459ebaff9cce"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.3+0/FLINT.v2.6.3.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "427f2299958c70f4d8397422a8a0f5ab022d03b6"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "0f744830aedfd72e85ab1d33ab5a30d27962a2a649ef5685f981f846682debff"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.3+0/FLINT.v2.6.3.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "8ee677e8f21af033cd4f0a3dd3a2e8120fb3a39f"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "fca5d76fae20fe79238354bf0bac7cc2721c288cf5a2333d2d0d004f08399217"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.3+0/FLINT.v2.6.3.x86_64-unknown-freebsd11.1.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "df03c73e27d945d9eaa954246c624d98650a3b8a"
os = "windows"

    [[FLINT.download]]
    sha256 = "e47b0721a8cd491fe49ed4d5a1bdc4cf5022eecb70ea763f1bce0a152db1551e"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v2.6.3+0/FLINT.v2.6.3.x86_64-w64-mingw32.tar.gz"
