[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "92f347b1555e9e5d21f6da1c8fd957fa40ebaa02"
os = "macos"

    [[FLINT.download]]
    sha256 = "660ef86ca878724503693327cbc698f620849ac5a6c862dcbe802a1dc66fea15"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.aarch64-apple-darwin.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "ccd7813c98bf518d57d7df0dfccd50534e406eb3"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "e987e3f1f0b9b3578537682fc92c387bbe6de81e42f1374931401db3c3fb2355"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "83236dd0c30b3f2563bed491682ee47e270aa59f"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "8fb82cc93da33c9d45c8c6cea7d67fd25ecd762b22601a42f28b0bb0631460c6"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7b23bd227d8280ad1419bac08ec787cf3240bc68"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "35723b64585d84b3d0ef23d4dcdf56f9538b9dc8fc38ff72718828b304b2ae9c"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.armv6l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "54f179a42d16fdc00727a29fe027c901a7305709"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "b6d69bfcda3c3d28017e09481fdb6569b57dec9afbb195fe19fae69e857748f7"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.armv6l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4f2898f4070e29564facbe5ce5b772b08919eef0"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "c8b43c44c6e95a9f8c1cfdf49bb7fd424e650cf8db1638a26feabe617ba67163"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4f8c0a3be16b6d6ba5d4b72379d6c92ff98c95de"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "b2191bb7ca1eb21e4e0548e7870587a04c1b4ad172bf37352d2e0a67afea1e1c"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "974dc7ba3f190ac17355dd04ba478998cf56e46d"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "e24ac4999c426a3c000b508e678c2fec98a1496646299890bdca3536f74d0a23"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "5198a86dd936ac683c8c756911a604af4f91d4ec"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "b1a03e6425fabc1c3fe8a92aa36013d125c42bbbd255a66b47804c91a0fe36e7"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "74b142a07ff66b5a7d59e9c9441018648c0d3da8"
os = "windows"

    [[FLINT.download]]
    sha256 = "44a52f6f08b64ef4374e79b5390c1b1d560f21ab29731664639f6ded3c86da8e"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "d6abd55b76cd72ac93d2c9791dc3738e103531dc"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "740f8dcb870b3b9dc5cb3a88b76b83881a6edf8328115d35e9beec0098d5abff"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "8b547594d5ec5ffabf8b2e8cb946c555cf8b8f3f"
os = "macos"

    [[FLINT.download]]
    sha256 = "25ce102ceea084f8c898dc4b0ce44b9e4196a9b0a0041e7fca27e058be350445"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.x86_64-apple-darwin.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "09609d1f3145d082f4aa2f1199377df625dd0e51"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "c8b65ba2af7e6877e6b1d7c35897ef457a2e2940013974361a691044edfa6680"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "d1e75435160abc7aeffd78e3fdd8a9f3dd7553ed"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "262371fa630326c15e0672cc6ffe8102b529d4b866669a880e469786067a1ad5"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "d4f3c787dd1136d5e7a783c7c3b79b9e6234e7ba"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "5b84ee5f8393f4fc1ae8e8b752debe29947bc66ef1dd44c34d0c8efb4201433e"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.x86_64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "11170ba320a02375352c461f847da313c104a5f2"
os = "windows"

    [[FLINT.download]]
    sha256 = "5bf0b75c0d15a4ce9df406fd77b5e20faddbeae903aece73617c87a76d5edd82"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.4+0/FLINT.v200.900.4.x86_64-w64-mingw32.tar.gz"
