[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "6eb7850a71bdbe9768c80f20f5056d5e59b07b94"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "19144bc4c528a1ac220650a43b449872f8cd8eb313a1dcd941831c2c37c5d282"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.700.0+0/FLINT.v200.700.0.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "06b68a28f96800087cd6388c95a0fef2cde430ef"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "322f223f3d598d4242c756c90d9b7ba2bbe23c18f2859c9b3ce717219d0ed920"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.700.0+0/FLINT.v200.700.0.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1043e635e38d5902877a54a6cb3ba89cccf748ce"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "a8d3acfeca3086a3fcbd31dfe830ae6f42f08d8ce4227d433bd488e86e42378b"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.700.0+0/FLINT.v200.700.0.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "92026b5bb3bcd3744c5fcfed398b6f3be4de6c0b"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "de4bae429a54baefe0ec1a1d12e29e7d377b908f0909ddefb89b33a89f8b4ec6"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.700.0+0/FLINT.v200.700.0.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "789525e89299cef627d26fad1604dedc3ede6eca"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "59306f1de33d98db074b0ab88719b18ea104dfffa2d0b2847729dbe1ee410119"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.700.0+0/FLINT.v200.700.0.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "5991399f7a7805feaaa7b8861bba21c6d2a7f2f3"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "560e6732bb0157720aa6ca9ff13b25cbadcecdee7efda0df62b889d516b5f1ef"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.700.0+0/FLINT.v200.700.0.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "b620b848074ea069ecd0a23ff7f5eafe697425f2"
os = "windows"

    [[FLINT.download]]
    sha256 = "95993643a90eeee855cce5a1d3cfbb75012e392861f09aea5252cc50a186ea2d"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.700.0+0/FLINT.v200.700.0.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "10e85d81f1fed9c37e859587ce274a87d425e4b0"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "229a5e87118fe62cb9eacbacffa65866b503936aec2adcd0582b476380cc0352"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.700.0+0/FLINT.v200.700.0.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "0b1249e6c610842ea4474823feb64bf6422056ce"
os = "macos"

    [[FLINT.download]]
    sha256 = "689188e19996f0ba4c6e8d255ef52ad2409d2bc1419585bb5e982bbbe97db863"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.700.0+0/FLINT.v200.700.0.x86_64-apple-darwin.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "ee2892b9cdffb5afb5438dcf7706c5be495abaae"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "108b501ff15353b1166878bfab5be41e835fe601b461432ae82cf83992572baf"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.700.0+0/FLINT.v200.700.0.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "2c33d002d0d2463ce678ddd185c9ff0b8a3de64e"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "4fa08e783194a906c077d211c2e0efadd5397d362d21e9075409284c8f74b23a"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.700.0+0/FLINT.v200.700.0.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "65b6f5feb55d726a8c70cdea70f4f89d331fd4e8"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "de711c6528a473b28ec73d685db18b6cc4bb5911fb4ebc2402039dfbbdf5f431"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.700.0+0/FLINT.v200.700.0.x86_64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "63657e58b38dbbaff8dabc82010dbe78d4810507"
os = "windows"

    [[FLINT.download]]
    sha256 = "726b7a6d80861e929dd1ad5d1082a97b9c06173f4cdb91e8e0e2d130e2464795"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.700.0+0/FLINT.v200.700.0.x86_64-w64-mingw32.tar.gz"
