[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "205e199b617f50cf141b54e91b3112ddbfd8ab6b"
os = "macos"

    [[FLINT.download]]
    sha256 = "bfc57d795914f79220f39d2ab570d374ee64400038cd84dc9a42e147ed26b72f"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.aarch64-apple-darwin.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "d8e5a1094636d567afd9af60c03a1bbad38276bc"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "8dd80da11413d42b6f43f51b566c593f4c702b22e8dd903b6a752d0b3505696e"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "200397ed851ade7bec2b2af769e403a846bc50e1"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "6ba6dd5f2b1436118194de193d19dba4dd3a96039f750e4a8b78edf32d5c7100"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "666dcedc87c70d821c6f4445b91371c685b5aa14"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "6a5352bed4d4043efc87fc172ffac280eff7b138ae50f22f69a887c69de93341"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.armv6l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "84fe09f79d4036e1925acee24c7a03d4fc645ae3"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "9dd2f122941148f6aff46123ddffddd8f7385bb08bc88621dbe2118f936e1034"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.armv6l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6d7fa1fcbe94091ff45bc16619cb07eff8ce2684"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "1a64f41116b13b12075e49804dc8ea45fcfa5915a34ac77cdc9464f2e46064c5"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9a75285ca06cbe970afd883c30a0c23655425110"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "4401ea1ded0d77c5375469de4e57bc5f2dca7e3e4756d303ac78daff54940ab9"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "eaa774e9a8dbd4610d167f802e5c7502eedd8824"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "1d4b08a59a4a627037b6123fc6779c0bc5b9281f108d031253344dc6f123270a"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "2c0d56b67f86ee60ef5dbbe1968af41c37ad70e1"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "d483b4c1d22798922a16070c29be46c979aaa95657531359bfa0a4bb8bcc93f9"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "4a8d6ecae121429ab6bbe82cee7dfde9f689ae76"
os = "windows"

    [[FLINT.download]]
    sha256 = "6416d802f61a79dff1ad5ee944c60e09d24a0327ecf6dbdd686ca0b3721cb356"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "5a7e33675e2a114bbb2961f5eeb6d819a72af6b8"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "560583dca3a236c4f852705b93313f34797de68bff866d5b14b4771b812bf520"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "dc91c96629c9a4bf32b8ea71826742a2ca4c8dd4"
os = "macos"

    [[FLINT.download]]
    sha256 = "c606a2a50330558b7a3f1b5e9164fccaadae19d88d454a384ac2c8fb7d204413"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.x86_64-apple-darwin.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "f8f79e4a4dc23a01314fbf7d20a7b580102d5cb3"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "2b613b203db1c38fd1d6301d0b45f744f580d87c3c6c18d46a4bb109b8797a9f"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "3d5d44b2e39b2ff7d74861575930638ff7777da3"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "c96b8044ee10621c2107d90f3b5b7e0acffd1fd322fc592c7b3b7a72d866ffd3"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "85a98764e4f6ddd53f24c5bfbb288d6faac9add8"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "fddc9f5157c2d17cc85ccd129b789c3e11b53e77c80c2cec3c8b10096a02b732"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.x86_64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "a90c5f5142fa91ce7005996dae4438df57bed051"
os = "windows"

    [[FLINT.download]]
    sha256 = "2e10b944cf10de20c22bbe3e190cf398954a6859e7136e45253e8551594dc7d4"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v300.0.0+0/FLINT.v300.0.0.x86_64-w64-mingw32.tar.gz"
