[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "2ef4c8060b93af14aec4462a610b33d37ca2d765"
os = "macos"

    [[FLINT.download]]
    sha256 = "4b36aec6142b68bb990bcfe7cf1b86e0fa44a1ffdf3f307aadd2dc7fca099c89"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.aarch64-apple-darwin.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "950f08bdd99d8dbfdb5959f593324b979737b9be"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "8afe507af0f445b678ed6f3b0461e79f5605e9bd4e681cd7b8d19256677f1ea2"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "39dae85a61f11b0f51b832e764e7d68e70e8de91"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "274657462c691d5938689e6966fa1a62d22aa142077cd21acdac35ee611f6642"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8519f516b17744eb7c1a5fd5c71b63d26f9702b2"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "f5fdc077e0ed15722d0834ad36a3e4f122e1d416e6db88fd5104625e761b5765"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.armv6l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0a23198283f20ae1238c1d988ee8d4bbb6186ec7"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "f53137faba05271bb3c26728dcdb23e1f891a7660e9a855bbfc9ce2c17901699"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.armv6l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c39c982952886f281acee1c099ddbbeac7376d9d"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "6b76ee3211e5eb9ffbf2bddb132eaa216a158d02bc9038c28456801789c7b223"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b7e0bc70a24037e62a32971e3df3375aa8901713"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "dfe763727222812af4daf6264c0c966d33f78eace46723b0127c0a2698871573"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "91950287a498cccc81c8aa6f1bd5256bfc4af61a"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "d64237d5914506ca4172ceab2f63b8e9b5685b90d20e3ba582b5460f7d00c87a"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "bdc0a18610103215fa2fb020c052257136b10bd1"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "89b2ad7e069f5beaaf1e6848c36cfb7f27f1f8143dfd5915ffdbfbceb7736b96"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "881e4868589c3948a0243ac89f2b3278dff82094"
os = "windows"

    [[FLINT.download]]
    sha256 = "a8db37cb81f60e3981b5f7a9df8f319b07c7ecd47471e5c71061a0b437d29da3"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "88d7a6844cc5d0853b6aea3e52fb45a35e0e3516"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "dd7a7a125c9bec15598c26599e66928259c71c31b7a8ce8b648ef9fea929a555"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "75caccf5bf54c328055a0e6153a6ab956db2507c"
os = "macos"

    [[FLINT.download]]
    sha256 = "b751561ad221d36f71b6fd5849b2ff63f85c990142a76da44a246ad341e4fbd3"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.x86_64-apple-darwin.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "b0b4f49b42f9457f451df63012de0b3a93f31592"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "f37688772ac47b0643cfb284ce12992fd0d0ad98e9f92bca2d8ae8c9d9cb592a"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "db3a087745d5e6b7f8908ca8e58a976c4f711876"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "e8bec7305bea030123cc72cb500f6915f3c6223f3f7f55a1b11cd1b1faba48f9"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "35a02cdf92a6d3347483cb6954004c3ca2f0ea89"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "650d7d607f52a2558908689d5ffb32f0f963887502ba0d0d0cc79fd12d133482"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.x86_64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "fd004c23a02e2e949c2a4022acdd4ccb1d0afe7e"
os = "windows"

    [[FLINT.download]]
    sha256 = "7c44cc5b2039c763c48b7acc9147f94c694f42f07936fd48917a3aa0cbf02692"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.3+0/FLINT.v200.900.3.x86_64-w64-mingw32.tar.gz"
