[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "e199e91119bb17695a63f9663a5858da560995f9"
os = "macos"

    [[FLINT.download]]
    sha256 = "5f808fc6e0e8e04a5a04ac50b7b3a819fdfd667f40b41c37a793419100719c75"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.aarch64-apple-darwin.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "c935414ace5f702c55400d330be5baf7aefc6bad"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "d28fac61411f4edd01143bfedccbf11511500183a71be111717fd7d9608c7b70"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "9946b22fba0ea2dd90ca6a875421fe952094a01d"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "3ccd71650fbbf983a4835db5fbdd3e6c7b7c3b461209a276ba63623f998c4eb1"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9d53c8b75d17384ccdec56fb7acaffd778f15522"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "4542c0ef4afbf88eb4ff6c678cf2c113aa1b8d847aa0b0d1a2b46a44e16ef8fc"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.armv6l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "981db73c53dfac6cf938416e72388f9f21972be0"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "f4a35b4ce773dc5e1d621cf99c0a353445470b70b29fcef26011e6335c925ded"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.armv6l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f34ffe4b85d5dd0d29d8578c6a987485bb57a810"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "12276f44bbe734bfa2981c8dab84d4abffa19679b4f202bb775c63faec67514a"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5b9c6755348ba5fcae95baae361d9d50d871fc62"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "38cc74843c4889a203678cc1b45b2cbb676c46ca98f4effe7d44b35aae6174b6"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "177cda65ddc786c75bb01609ea52eac85808fde2"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "20fb5172aa3f5bf797f7a0f966d4167eff850ca5c5f0c5c600f3c877b201f9ad"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "a7c4fdcfe1c4edf94bbabdd722056f504cc3b1ca"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "1da3a830932d75e15fefca16cd94ee6f4c1bc976a3a62de6be80f10a270e9efb"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "06cf94da0a7cd572eaa17e0ed63c9a6b16208309"
os = "windows"

    [[FLINT.download]]
    sha256 = "db43e7ddcb7ba0ae549fa7f89a344d961191499eb2adb4d02a9c00fb121543e1"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "9cd53303716a625f505865bba3a117d9b1dbf268"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "38f8d94a90687f4442bfc3938f4c1f7edf70644b237f132ee4f1c3eb95a42627"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "3046792f247eda1f9ff801cab86b0ffb8fee0a94"
os = "macos"

    [[FLINT.download]]
    sha256 = "67c1db376dc576dfe6aa9b4942050a09c527de240e63b670bb3ade442e9a3fef"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.x86_64-apple-darwin.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "c4cc26174338190275ffa85e40bde125d7d54e85"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "0d1dcbd69f23adfc3dcf521c2e59bb82374bc39b4f6e9515628f123d24aece08"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "ec9cda61704ced1e867dd82a3b4a9bdfd6885de9"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "88192375f45949a8f4c396f246cc968cf286f9db1ac0bc8c4083d7ed2d087c42"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "9184d4b5bf2a4e549b4b333004ad27cf1404e451"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "e741b3e82e08fb03a797d63a9ae8e0e559d6b087bacb0f497804b28d4211672f"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.x86_64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "b292188256d72493627ee874b450a860b395b7f0"
os = "windows"

    [[FLINT.download]]
    sha256 = "d9d6e803d3a5cc8bccf9b634306555ae33de1f05ad8cda208204d6a9b5129bb8"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.0+0/FLINT.v200.900.0.x86_64-w64-mingw32.tar.gz"
