[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "29e67ea9d3ef040dc193de4c9074ab7d89babffc"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "fc033381212b0003e92a12e6fb767a61b252ecde69c9ae7f4504bb1993a33ad6"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v0.0.2+0/FLINT.v0.0.2.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "95187ea9a52028a33e2ec5c38654d7c98954ca1d"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "823b8217daffea6f59c2e91e7b422ec0bc45fe5db82fbe92c0f112f363a08d27"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v0.0.2+0/FLINT.v0.0.2.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "armv7l"
git-tree-sha1 = "51751f85e6202539b6ecb236c1edc417ab621b5d"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "aa17f15edadb72b30c26a36290e4e23fb142a69d6ab9978ed6115b1671e735ce"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v0.0.2+0/FLINT.v0.0.2.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
git-tree-sha1 = "5e43caae80b024feb0896062dfbf120e7667f4b0"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "02157189f548864fb24fee348ab775f5e5ac1bc8a144a7e5ed2b3dd2a1293fab"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v0.0.2+0/FLINT.v0.0.2.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "d2dd50801c326286fda22532c72cc4d4d627583e"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "09e7104c54e27f71d0384562267682b9c23382535abcbfa8773c8d8a607b5a20"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v0.0.2+0/FLINT.v0.0.2.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "aedc6ac704d44021d714fb553d4c8ca706472e10"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "82d1acb1fd5e363f2567cbde793086c6b0040dafa7cfbf0444339dfe9f98b743"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v0.0.2+0/FLINT.v0.0.2.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "814a7412d0593fadcc4867ec4e977a1c538fa0e1"
os = "windows"

    [[FLINT.download]]
    sha256 = "5e68cfeac5f5cfbf4f6ed0bad185274135d3751fa74a52bcb19e3d3ed4a6733d"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v0.0.2+0/FLINT.v0.0.2.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "23350fd361e489fc2c6e58fa127749a3a4aa5c98"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "424f200d1f821ee40bc67e0728ca71378490c94756849e5e08dd599a47ef9a4e"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v0.0.2+0/FLINT.v0.0.2.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "5385a18ca285a9fcf3b0cd3bf88c52d54fba18b6"
os = "macos"

    [[FLINT.download]]
    sha256 = "47fa6fe4f46f084f585c7665838acb66dddebf812342911a70bec07116162e84"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v0.0.2+0/FLINT.v0.0.2.x86_64-apple-darwin14.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "25e97f5981481be2ac06c6290124cd331fc74d50"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "f065650c4eaae77d7234232e279f91cfc892b1d44588792178154ee20164f95c"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v0.0.2+0/FLINT.v0.0.2.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "61ca603fbab9541b0abfc9fffa2be1f26c479d6f"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "4f212be5c9ffc38b50aaa69a4c63df505bcdc02099c31494fabd64c337bf52ba"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v0.0.2+0/FLINT.v0.0.2.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "c9759da7538a07b8c8220682c110fe9901e97c41"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "4a679118435961a358cfbbf68eb4ea781694d53a493929b78309690b2341a86d"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v0.0.2+0/FLINT.v0.0.2.x86_64-unknown-freebsd11.1.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "d70435ccb83188fdd15783cd65c35d27b853d81b"
os = "windows"

    [[FLINT.download]]
    sha256 = "94900de41b267a2f0d117fa4cdbbfc73c9c215ed94dcf746a9e736664be9a644"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v0.0.2+0/FLINT.v0.0.2.x86_64-w64-mingw32.tar.gz"
