[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "fdd38ca0ff883c509a224270243bffd3ccfc5abc"
os = "macos"

    [[FLINT.download]]
    sha256 = "afc91a19e32a16a0014f9aeb4588baf4dc61a542d54f23f4115c7cde0221a0c9"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.aarch64-apple-darwin.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "6b65780b6b0744e15b8a46dc05bcf19662b05741"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "4edc2c8bb0cb4f2be9971a9b2e9a0a8c6e7f9522d0b4f33b32dbe077d25dfac5"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "378ec7e61f8be50661ff1ef695c3d9817e018d03"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "504cdc0c9efd0f717be1fc5d63f38a0a6ba81d67b013581de3c971aa40c1b08e"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4ce472ebac5e01107b31a772c33368e136593d2d"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "9af6206b1991b2fdc34ec1744a39f96822e568ea789467129090b78891dfb26e"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.armv6l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "01f9f669a36e4d01f0f5a77836a286177588e236"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "ec6a58ecd82b7d579c12f9f4cb0626670f9eb18c50765d47f14b6307d5b32516"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.armv6l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "616a7617d2da4569c44002613572120cdd0bda2f"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "4d1816a3a55d316df104b26fd0aff9d258c686337a34332640b1fb9c2726dbdf"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "16b4b05a85eebaefc07da22091b1d518c58e3ca5"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "7d33ffcb60b4a9fe14001e6d0e72ea95d38102b30f58436c1c216135e99b9432"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "ea2b174458ebd9a93991be99958d531a7366ef00"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "a90ed38dc18cd66a4718f1677a727dd392206d1456788ceba19d64ab320fb1c3"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "bb79482d785d9ef7dc921504eb03d2440f44764c"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "a0e9c1101109dc84a0e41ea023821ba421dcd3349a859ab3028debfd84602e5b"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "0278de0db3ee86bcd9f9557183770b5984d47149"
os = "windows"

    [[FLINT.download]]
    sha256 = "77e2b4ca46a14331e1b68d2fd24378a00180ea8bf3ee81554292c811efeea9bf"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "a0aadd34d57d6bed3b9756999c8243c95fcb2f12"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "35d980bbeab961e4c06dd9d0b459325bdd60275f01fd31f6215d46935026cbd7"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "fb638b0a4d7c291af8ccc123059c1335eca5ff4c"
os = "macos"

    [[FLINT.download]]
    sha256 = "cfaea53dbeb67627380da1f0284b7d2b3da30838ef6e18caccd6e5a952dc0650"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.x86_64-apple-darwin.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "28d4f50cc0733379eb21121738a86b414ae89b7c"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "ccda93fccba14823c68dacb3f0cb4c72a63ae2585cc811a377eb3ef0c8771919"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "0e144bdbd71cfc2e9f2281c010a00a6128108657"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "72fc8c06e39c2b5bc077cc6827f3d584e73e600d29f58f184d496607280f9175"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "076dc9fc82c647912af3efe430ebe538c4bcbac1"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "412f0b2ba327e8d5f0f726021aa4d17c4a769e902b24c6ce21a8ae20ad615d1e"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.x86_64-unknown-freebsd.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "27594225e810a146b6c850c51aa5b422cd6f661c"
os = "windows"

    [[FLINT.download]]
    sha256 = "1570057d252b9a6d1faebac8546b210c6435f72355b401dae2cec4c6d5e9aa95"
    url = "https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/releases/download/FLINT-v200.900.1+0/FLINT.v200.900.1.x86_64-w64-mingw32.tar.gz"
